Develop
Obote/Awesome-books-Es6 pull request #1
Opened 2022-02-14 22:25 UTC by Obote

### **Restructuring my Awesome books app code**
Setup your project:

- Create a new directory and initialize it with git.

> - Use npm init -y command to create package.json file.
> - Create the entry point for your JavaScript code called index.js
> - Create index.css file for your styles.
> - Create the main index.html file. Link your index.js and index.css files there.
> - Create a directory called modules.
- Re-create your Awesome books app following the rules:
> - Use ES6 syntax.
> - Divide your code into modules. Save each module in a separate file in the modules dir. Import modules in the index.js file. For this exercise - the more modules the better!
> - Keep all functionalities of the app without errors.
- Display the current date below the navigation bar. - For this requirement you should use a library - Luxon
> - Install it as a npm package: npm install --save luxon.
> - Import it as a module.
> - See the article Get the current date and time. Your task here is to use a new tool effectively with little externally curated support. Exactly as you will do in your future job.

2022-02-14 22:38 UTC, moise10r requested changes
### Hi **@Obote**

You did a great job so far 👏🏼 👏🏼
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

### To highlight 💪🏻

- No linter errors. ✔️   
- Professional README ✔️ 
- The current date is displayed below the navigation bar :heavy_check_mark: 
- Your Design looks awesome, keep rocking :rocket: 
 👍  Good job!


## STATUS: CHANGES REQUESTED  ♻️ 
_Please Check the comments under the review and make all required changes_

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding!👏👏👏 💻  
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please ping me @moise10r when you comment so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-14 22:38 UTC, moise10r commented on index.js
> +}
- [ ] Great job for the displayDate() function implementation, :clap: but I think it will be better if you can use arrow syntax for functions instead of a  function declaration for more information [JavaScript Function Expressions](https://www.w3docs.com/learn-javascript/function-expressions.html)

2022-02-14 22:41 UTC, moise10r commented on modules/navigationbar.js
> +
- [ ] Great job for the displayDate() function implementation, :clap: but I think it will be better if you can use arrow syntax for functions instead of a  function declaration for more information [JavaScript Function Expressions](https://www.w3docs.com/learn-javascript/function-expressions.html)

2022-02-16 03:46 UTC, Rustamxon7 approved these changes
## Hi @Obote   👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
## Congratulations! 🎉 🎉 🎉 🎉 🎉 

Cheers and Happy coding!👏👏👏

![Developer-512px-10](https://user-images.githubusercontent.com/69011963/151541305-67f4f8e4-c79e-4f9d-a6cf-2c7efc3102c6.gif)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2022-02-16 03:47 UTC, merged